
* Simulation programs under =test=

** Diagnostics

- Temperature: average and z-profile
- Density z-profile
- Number of filled cells

** setup_simple_fluid

Define a periodic pure MPCD fluid.

** setup_thermal_fluid

Define a pure MPCD fluid periodic in x and y and under a temperature
gradient in z.

* features, existing and to come

** flow tolerant temperature computation

The temperature is computed cell-wise to eliminate the c.o.m. kinetic
energy locally.

** bounce-back walls for the solvent

Implemented in z only.

*** allow bounce back along two directions

This is useful to couple a gravity driven flow in z. It might be
useless if gravity implented in y direction, though.

** TODO robust neighbour listing

Should work automatically given a cut-off radius.

** thermal boundary conditions

Implemented via virtual wall particles.

** gravity

Not implemented.

** bulk thermostatting

Not implemented.

** bulk rmpcd

Not implemented.

** MD

Not implemented.

** external field on colloid

Not implemented.


* neighbor listing

** encompassing cubes or spheres

add cell system with side rc + skin, visit 27-cube

spherical count = rho * 4/3 pi (rc+skin)^3
cubic count = rho * (3*(rc+skin))^3

cubic count / spherical count = 27 / (4/3 pi)

** cell lists

* References

** Foundational

- MPCD and MPCDMD papers by Malevanets and Kapral
- RMPCD paper

** Thermal gradient

Lusebrink and Ripoll, J. Chem. Phys. 136, 084106 (2012)

** gravity
