set(CMAKE_FIND_LIBRARY_SUFFIXES ".a;.la;.so;.dylib")
IF(NOT HDF5_ROOT)
MESSAGE(FATAL_ERROR "HDF5_ROOT undefined, stopping")
ENDIF(NOT HDF5_ROOT)

FIND_LIBRARY(HDF5LIB hdf5 PATHS ${HDF5_ROOT} PATH_SUFFIXES lib NO_DEFAULT_PATH)
FIND_LIBRARY(HDF5FORTRANLIB hdf5_fortran PATHS ${HDF5_ROOT} PATH_SUFFIXES lib NO_DEFAULT_PATH)
FIND_PATH(HDF5_INC hdf5.mod PATHS ${HDF5_ROOT} PATH_SUFFIXES lib include NO_DEFAULT_PATH)
